import { clone, createDefinitionFactory, defineInjectedRuntimeKit, ensureResource, stableId } from "../protokit-core/index.js";

export const QUATERNIUS_PACK_LIBRARY_KIT_VERSION = "0.1.0";

export const QUATERNIUS_PACKS = Object.freeze([
  { id: "quaternius-universal-base-characters", family: "characters", license: "CC0", formats: ["fbx", "gltf"], features: ["base-bodies", "hair-styles", "skin-colors", "eye-colors", "humanoid-rig", "ual-compatible"] },
  { id: "quaternius-modular-character-outfits-fantasy", family: "outfits", license: "CC0", formats: ["fbx", "gltf"], features: ["outfit-slots", "modular-parts", "texture-variants", "humanoid-rig", "ual-compatible"] },
  { id: "quaternius-universal-animation-library-one", family: "animations", license: "CC0", formats: ["fbx", "gltf", "blend"], features: ["idle", "walk", "run", "sprint", "crawl", "swim", "sit", "combat", "gun", "emote", "death"] },
  { id: "quaternius-universal-animation-library-two", family: "animations", license: "CC0", formats: ["fbx", "gltf", "blend"], features: ["melee-combo", "armed-combo", "parkour", "farming", "fishing", "zombie", "recoveries"] },
  { id: "quaternius-stylized-nature-megakit", family: "world-pieces", license: "CC0", formats: ["fbx", "gltf", "blend"], features: ["trees", "plants", "rocks", "grass", "biome-decoration"] },
  { id: "quaternius-downtown-city-megakit", family: "world-pieces", license: "CC0", formats: ["fbx", "gltf", "blend"], features: ["city-buildings", "streets", "fake-interiors", "simple-collisions"] },
  { id: "quaternius-modular-scifi-megakit", family: "world-pieces", license: "CC0", formats: ["fbx", "gltf", "blend"], features: ["rooms", "corridors", "doors", "panels", "emissive", "shader-masks"] },
  { id: "quaternius-fantasy-props-megakit", family: "props", license: "CC0", formats: ["fbx", "gltf", "blend"], features: ["furniture", "tools", "weapons", "books", "potions", "breakables"] }
]);

export const QUATERNIUS_BASE_CHARACTERS = Object.freeze(["regular-female", "regular-male", "teen-female", "teen-male", "superhero-female", "superhero-male"].map((id) => ({ id, rig: "humanoid", proportion: id.split("-")[0], compatibleAnimationBanks: ["ual-one", "ual-two"] })));
export const QUATERNIUS_HAIR_STYLES = Object.freeze(Array.from({ length: 20 }, (_, index) => ({ id: `hair-${String(index + 1).padStart(2, "0")}`, slot: "hair" })));
export const QUATERNIUS_SKIN_COLORS = Object.freeze(["fair", "warm-light", "warm-medium", "tan", "brown", "deep"].map((id) => ({ id, kind: "skin" })));
export const QUATERNIUS_EYE_COLORS = Object.freeze(["brown", "blue", "green", "gray", "amber"].map((id) => ({ id, kind: "eyes" })));
export const QUATERNIUS_OUTFIT_PARTS = Object.freeze([
  { id: "ranger-tunic-a", slot: "torso", variants: ["green", "brown", "blue"] },
  { id: "ranger-pants-a", slot: "legs", variants: ["green", "brown", "blue"] },
  { id: "leather-boots-b", slot: "boots", variants: ["brown", "black", "tan"] },
  { id: "fingerless-gloves-a", slot: "gloves", variants: ["brown", "black", "tan"] },
  { id: "knight-armor-a", slot: "torso", variants: ["steel", "dark", "gold"] },
  { id: "mage-cape-a", slot: "cape", variants: ["blue", "red", "purple"] }
]);
export const QUATERNIUS_EQUIPMENT = Object.freeze([
  { id: "short-sword", slot: "rightHand", category: "melee", animations: ["melee-combo", "armed-combo"] },
  { id: "wooden-shield", slot: "leftHand", category: "shield", animations: ["armed-combo", "block"] },
  { id: "fishing-rod", slot: "rightHand", category: "tool", animations: ["fishing"] },
  { id: "watering-can", slot: "rightHand", category: "tool", animations: ["farming"] },
  { id: "scifi-rifle", slot: "rightHand", category: "gun", animations: ["gun"] }
]);
export const QUATERNIUS_ANIMATION_CATEGORIES = Object.freeze(["idle", "walk", "run", "sprint", "strafe", "crawl", "swim", "sit", "death", "combat", "gun", "emote", "melee-combo", "armed-combo", "parkour", "farming", "fishing", "zombie"]);
export const QUATERNIUS_ANIMATION_CLIPS = Object.freeze([
  { id: "ual1-idle", bank: "ual-one", semantic: "idle", rootMotion: "in-place", required: true },
  { id: "ual1-walk-forward", bank: "ual-one", semantic: "walk", rootMotion: "in-place", required: true },
  { id: "ual1-run-forward", bank: "ual-one", semantic: "run", rootMotion: "in-place", required: true },
  { id: "ual1-sprint-forward", bank: "ual-one", semantic: "sprint", rootMotion: "in-place" },
  { id: "ual1-gun-idle", bank: "ual-one", semantic: "gun", rootMotion: "in-place" },
  { id: "ual2-melee-combo-3", bank: "ual-two", semantic: "melee-combo", rootMotion: "explicit" },
  { id: "ual2-parkour-vault", bank: "ual-two", semantic: "parkour", rootMotion: "explicit" },
  { id: "ual2-farming-hoe", bank: "ual-two", semantic: "farming", rootMotion: "in-place" },
  { id: "ual2-fishing-cast", bank: "ual-two", semantic: "fishing", rootMotion: "in-place" },
  { id: "ual2-zombie-walk", bank: "ual-two", semantic: "zombie", rootMotion: "in-place" }
]);
export const QUATERNIUS_HUMANOID_RIG = Object.freeze({ id: "quaternius-humanoid-rig", requiredBones: ["root", "hips", "spine", "chest", "neck", "head", "leftUpperArm", "leftLowerArm", "leftHand", "rightUpperArm", "rightLowerArm", "rightHand", "leftUpperLeg", "leftLowerLeg", "leftFoot", "rightUpperLeg", "rightLowerLeg", "rightFoot"], restPose: "a-pose-or-t-pose", sourceBanks: ["ual-one", "ual-two"] });
export const QUATERNIUS_MATERIAL_ATLAS = Object.freeze([{ id: "character-atlas", family: "characters" }, { id: "outfit-atlas", family: "outfits" }, { id: "world-atlas", family: "world-pieces" }]);

export const QUATERNIUS_WEBGPU_CHARACTER_WGSL = /* wgsl */ `
struct Camera { viewProj: mat4x4<f32>, lightDir: vec4<f32> };
struct Material { baseColor: vec4<f32>, shadeSteps: f32, rimStrength: f32, pad0: vec2<f32> };
@group(0) @binding(0) var<uniform> camera: Camera;
@group(1) @binding(0) var<uniform> material: Material;
struct VertexIn { @location(0) position: vec3<f32>, @location(1) normal: vec3<f32>, @location(2) uv: vec2<f32> };
struct VertexOut { @builtin(position) clip: vec4<f32>, @location(0) normal: vec3<f32>, @location(1) uv: vec2<f32> };
@vertex fn vs_main(input: VertexIn) -> VertexOut { var out: VertexOut; out.clip = camera.viewProj * vec4<f32>(input.position, 1.0); out.normal = input.normal; out.uv = input.uv; return out; }
@fragment fn fs_main(input: VertexOut) -> @location(0) vec4<f32> { let ndl = max(dot(normalize(input.normal), normalize(camera.lightDir.xyz)), 0.0); let stepped = floor(ndl * material.shadeSteps) / max(material.shadeSteps - 1.0, 1.0); return vec4<f32>(material.baseColor.rgb * stepped, material.baseColor.a); }
`;
export const QUATERNIUS_WEBGPU_TERRAIN_WGSL = /* wgsl */ `
struct Camera { viewProj: mat4x4<f32>, lightDir: vec4<f32> };
struct TerrainMaterial { lowColor: vec4<f32>, highColor: vec4<f32>, slopeColor: vec4<f32>, heightScale: f32, pad0: vec3<f32> };
@group(0) @binding(0) var<uniform> camera: Camera;
@group(1) @binding(0) var<uniform> terrainMaterial: TerrainMaterial;
struct VertexIn { @location(0) position: vec3<f32>, @location(1) normal: vec3<f32> };
struct VertexOut { @builtin(position) clip: vec4<f32>, @location(0) normal: vec3<f32>, @location(1) height: f32 };
@vertex fn vs_main(input: VertexIn) -> VertexOut { var out: VertexOut; out.clip = camera.viewProj * vec4<f32>(input.position, 1.0); out.normal = input.normal; out.height = input.position.y; return out; }
@fragment fn fs_main(input: VertexOut) -> @location(0) vec4<f32> { let shade = max(dot(normalize(input.normal), normalize(camera.lightDir.xyz)), 0.25); let h = clamp(input.height / max(terrainMaterial.heightScale, 0.001), 0.0, 1.0); let color = mix(terrainMaterial.lowColor, terrainMaterial.highColor, h); return vec4<f32>(color.rgb * shade, color.a); }
`;

const asList = (value) => value == null ? [] : Array.isArray(value) ? value.slice() : [value];
const byId = (items) => Object.fromEntries(asList(items).filter((item) => item?.id).map((item) => [item.id, item]));
const ext = (path = "") => String(path).split("?")[0].split("#")[0].split(".").pop()?.toLowerCase() ?? "";
const safeRuntimePath = (path = "") => String(path).startsWith("public/assets/") || String(path).startsWith("/assets/") || String(path).startsWith("./assets/");
function initialState(overrides = {}) { return { version: QUATERNIUS_PACK_LIBRARY_KIT_VERSION, packs: clone(QUATERNIUS_PACKS), characters: clone(QUATERNIUS_BASE_CHARACTERS), hairStyles: clone(QUATERNIUS_HAIR_STYLES), skinColors: clone(QUATERNIUS_SKIN_COLORS), eyeColors: clone(QUATERNIUS_EYE_COLORS), outfitParts: clone(QUATERNIUS_OUTFIT_PARTS), equipment: clone(QUATERNIUS_EQUIPMENT), animationClips: clone(QUATERNIUS_ANIMATION_CLIPS), materialAtlases: clone(QUATERNIUS_MATERIAL_ATLAS), receipts: [], files: [], runtimeAssets: [], recipes: [], ...overrides }; }
function defineKit(nexusEngine, config) { const { resource } = createDefinitionFactory(nexusEngine); const State = resource(config.resourceName ?? `${config.surface}.state`); const initial = () => initialState(config.initial ?? {}); return defineInjectedRuntimeKit(nexusEngine, { id: config.id, resources: { State }, provides: asList(config.provides ?? config.id), initWorld({ world }) { ensureResource(world, State, initial); }, install({ engine, world }) { const state = () => ensureResource(world, State, initial); engine.n = engine.n ?? {}; engine.n[config.surface] = config.createApi({ state, engine, world, State }); if (config.alias) engine[config.alias] = engine.n[config.surface]; }, metadata: { version: QUATERNIUS_PACK_LIBRARY_KIT_VERSION, stability: "prototype", purpose: config.id } }); }
export function classifyQuaterniusFile(path = "") { const extension = ext(path); const kind = extension === "glb" || extension === "gltf" ? "runtime-model" : extension === "fbx" || extension === "obj" ? "source-model" : extension === "blend" ? "source-scene" : ["png", "jpg", "jpeg", "webp"].includes(extension) ? "texture" : extension === "zip" ? "archive" : "unknown"; return { path: String(path), extension, kind, safeRuntimePath: safeRuntimePath(path) }; }
export function validateCharacterRecipe(recipe = {}, state = initialState()) { const issues = []; if (!byId(state.characters)[recipe.base?.body]) issues.push(`invalid-body:${recipe.base?.body ?? "missing"}`); if (recipe.appearance?.hair && !byId(state.hairStyles)[recipe.appearance.hair]) issues.push(`invalid-hair:${recipe.appearance.hair}`); if (recipe.appearance?.skin && !byId(state.skinColors)[recipe.appearance.skin]) issues.push(`invalid-skin:${recipe.appearance.skin}`); if (recipe.appearance?.eyes && !byId(state.eyeColors)[recipe.appearance.eyes]) issues.push(`invalid-eyes:${recipe.appearance.eyes}`); return { ok: issues.length === 0, issues }; }
export function createCharacterRecipe(input = {}, state = initialState()) { const body = input.base?.body ?? "regular-female"; const recipe = { id: input.id ?? stableId("quaternius-character", body, input.appearance?.hair ?? "hair-01", input.appearance?.skin ?? "warm-medium", input.appearance?.eyes ?? "green"), base: { pack: "quaternius-universal-base-characters", body, proportion: state.characters.find((entry) => entry.id === body)?.proportion ?? "regular" }, appearance: { hair: input.appearance?.hair ?? "hair-01", skin: input.appearance?.skin ?? "warm-medium", eyes: input.appearance?.eyes ?? "green" }, outfit: input.outfit ?? {}, equipment: input.equipment ?? {}, animationBank: input.animationBank ?? "quaternius-animation-library-one", runtimeProfile: input.runtimeProfile ?? "third-person-terrain-walker" }; return { ...recipe, validation: validateCharacterRecipe(recipe, state) }; }
export function validateOutfitRecipe(outfit = {}, state = initialState()) { const issues = []; const parts = byId(state.outfitParts); for (const [slot, partId] of Object.entries(outfit)) { if (slot === "colorVariant" || partId == null) continue; const part = parts[partId]; if (!part) issues.push(`unknown-outfit-part:${partId}`); else if (part.slot !== slot) issues.push(`slot-mismatch:${slot}:${partId}:${part.slot}`); } return { ok: issues.length === 0, issues }; }
export function checkRigBinding(targetRig = {}, clip = {}) { const targetBones = new Set(asList(targetRig.bones ?? targetRig.requiredBones ?? QUATERNIUS_HUMANOID_RIG.requiredBones)); const missingBones = QUATERNIUS_HUMANOID_RIG.requiredBones.filter((bone) => !targetBones.has(bone)); const tracks = new Set(asList(clip.tracks ?? QUATERNIUS_HUMANOID_RIG.requiredBones)); const missingTracks = QUATERNIUS_HUMANOID_RIG.requiredBones.filter((bone) => !tracks.has(bone)); const issues = [...missingBones.map((bone) => `missing-bone:${bone}`), ...missingTracks.map((bone) => `missing-track:${bone}`)]; return { status: issues.length === 0 ? "ready" : missingBones.length <= 2 ? "needs-conversion" : "failed", missingBones, missingTracks, rootMotion: clip.rootMotion ?? "unknown", issues }; }
export function createShaderDescriptor(id, source, fallback = "three-mesh-standard") { return { id, language: "wgsl", source, stages: { vertex: "vs_main", fragment: "fs_main" }, bindGroups: [{ group: 0, bindings: [{ binding: 0, type: "uniform-buffer" }] }, { group: 1, bindings: [{ binding: 0, type: "uniform-buffer" }] }], fallback }; }
export const QUATERNIUS_CHARACTER_SHADER_DESCRIPTOR = Object.freeze(createShaderDescriptor("quaternius-webgpu-character-shader", QUATERNIUS_WEBGPU_CHARACTER_WGSL));
export const QUATERNIUS_TERRAIN_SHADER_DESCRIPTOR = Object.freeze(createShaderDescriptor("quaternius-webgpu-terrain-shader", QUATERNIUS_WEBGPU_TERRAIN_WGSL, "three-terrain-standard"));

export function createQuaterniusPackLibraryKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-pack-library-kit", surface: options.surface ?? "quaterniusPackLibrary", alias: "quaterniusPackLibrary", provides: ["quaternius-pack-library", "quaternius-pack-query"], createApi: ({ state }) => ({ snapshot: () => clone(state()), listPacks: () => clone(state().packs), getPack: (id) => clone(state().packs.find((pack) => pack.id === id) ?? null), listCharacters: () => clone(state().characters), listAnimations: () => clone(state().animationClips), listOutfitParts: () => clone(state().outfitParts), listRuntimeAssets: () => clone(state().runtimeAssets), validate: () => ({ ok: state().packs.every((pack) => pack.id && pack.license === "CC0"), count: state().packs.length }) }) }); }
export function createQuaterniusPackCatalogKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-pack-catalog-kit", surface: options.surface ?? "quaterniusPackCatalog", createApi: ({ state }) => ({ snapshot: () => ({ packs: clone(state().packs) }), listPacks: () => clone(state().packs), getPack: (id) => clone(state().packs.find((pack) => pack.id === id) ?? null), listByFamily: (family) => clone(state().packs.filter((pack) => pack.family === family)), validate: () => ({ ok: state().packs.every((pack) => pack.id && pack.family), count: state().packs.length }) }) }); }
export function createQuaterniusLicenseReceiptKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-license-receipt-kit", surface: options.surface ?? "quaterniusLicenseReceipt", createApi: ({ state }) => ({ snapshot: () => clone(state().receipts), recordReceipt(receipt = {}) { const next = { id: receipt.id ?? stableId("license-receipt", receipt.packId, receipt.sourceUrl), license: receipt.license ?? "CC0", ...receipt }; state().receipts = [...state().receipts.filter((item) => item.id !== next.id), next]; return clone(next); }, validateReceipt: (receipt = {}) => ({ ok: Boolean(receipt.packId && receipt.sourceUrl && (receipt.license ?? "CC0") === "CC0"), issues: [!receipt.packId && "missing-pack-id", !receipt.sourceUrl && "missing-source-url", (receipt.license ?? "CC0") !== "CC0" && "license-not-cc0"].filter(Boolean) }) }) }); }
export function createQuaterniusFileIndexKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-file-index-kit", surface: options.surface ?? "quaterniusFileIndex", createApi: ({ state }) => ({ snapshot: () => clone(state().files), classifyFile: classifyQuaterniusFile, indexFiles(files = []) { const indexed = asList(files).map((file) => typeof file === "string" ? classifyQuaterniusFile(file) : { ...classifyQuaterniusFile(file.path), ...file }); state().files = [...state().files, ...indexed]; return clone(indexed); }, listByKind: (kind) => clone(state().files.filter((file) => file.kind === kind)) }) }); }
export function createQuaterniusRuntimePromotionKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-runtime-promotion-kit", surface: options.surface ?? "quaterniusRuntimePromotion", createApi: ({ state }) => ({ snapshot: () => clone(state().runtimeAssets), canPromote(asset = {}) { const path = asset.runtimePath ?? asset.path ?? ""; const issues = [!safeRuntimePath(path) && "unsafe-runtime-path", ["exe", "sh", "bat", "cmd", "js"].includes(ext(path)) && "unsafe-extension", asset.approved !== true && "asset-not-approved"].filter(Boolean); return { ok: issues.length === 0, issues }; }, promoteAsset(asset = {}) { const result = this.canPromote(asset); if (!result.ok) return { ok: false, issues: result.issues, asset: clone(asset) }; const promoted = { id: asset.id ?? stableId("runtime-asset", asset.runtimePath ?? asset.path), ...asset, promoted: true }; state().runtimeAssets = [...state().runtimeAssets.filter((item) => item.id !== promoted.id), promoted]; return { ok: true, asset: clone(promoted) }; } }) }); }
export function createQuaterniusBaseCharacterKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-base-character-kit", surface: options.surface ?? "quaterniusBaseCharacter", createApi: ({ state }) => ({ snapshot: () => clone(state().characters), listBodies: () => clone(state().characters), getBody: (id) => clone(state().characters.find((body) => body.id === id) ?? null), listHairStyles: () => clone(state().hairStyles), listSkinColors: () => clone(state().skinColors), listEyeColors: () => clone(state().eyeColors) }) }); }
export function createQuaterniusCharacterCreatorKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-character-creator-kit", surface: options.surface ?? "quaterniusCharacterCreator", createApi: ({ state }) => ({ snapshot: () => clone(state().recipes), createRecipe(input = {}) { const recipe = createCharacterRecipe(input, state()); state().recipes = [...state().recipes.filter((item) => item.id !== recipe.id), recipe]; return clone(recipe); }, updateBase(recipe, body) { return this.createRecipe({ ...recipe, base: { ...(recipe.base ?? {}), body } }); }, updateHair(recipe, hair) { return this.createRecipe({ ...recipe, appearance: { ...(recipe.appearance ?? {}), hair } }); }, updateSkin(recipe, skin) { return this.createRecipe({ ...recipe, appearance: { ...(recipe.appearance ?? {}), skin } }); }, updateEyes(recipe, eyes) { return this.createRecipe({ ...recipe, appearance: { ...(recipe.appearance ?? {}), eyes } }); }, validateRecipe: (recipe) => validateCharacterRecipe(recipe, state()), exportRecipe: (recipe) => JSON.stringify(recipe, null, 2) }) }); }
export function createQuaterniusOutfitBuilderKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-outfit-builder-kit", surface: options.surface ?? "quaterniusOutfitBuilder", createApi: ({ state }) => ({ snapshot: () => clone({ parts: state().outfitParts }), listParts: () => clone(state().outfitParts), listSlots: () => [...new Set(state().outfitParts.map((part) => part.slot))], validateOutfit: (outfit) => validateOutfitRecipe(outfit, state()), buildOutfit(outfit = {}) { return { outfit: clone(outfit), validation: validateOutfitRecipe(outfit, state()) }; } }) }); }
export function createQuaterniusEquipmentBuilderKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-equipment-builder-kit", surface: options.surface ?? "quaterniusEquipmentBuilder", createApi: ({ state }) => ({ snapshot: () => clone(state().equipment), listEquipment: () => clone(state().equipment), listBySlot: (slot) => clone(state().equipment.filter((item) => item.slot === slot)), animationMapFor: (id) => clone(state().equipment.find((item) => item.id === id)?.animations ?? []) }) }); }
export function createQuaterniusAnimationLibraryOneKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-animation-library-one-kit", surface: options.surface ?? "quaterniusAnimationLibraryOne", createApi: ({ state }) => ({ snapshot: () => clone(state().animationClips.filter((clip) => clip.bank === "ual-one")), listClips: () => clone(state().animationClips.filter((clip) => clip.bank === "ual-one")), listCategories: () => [...new Set(state().animationClips.filter((clip) => clip.bank === "ual-one").map((clip) => clip.semantic))] }) }); }
export function createQuaterniusAnimationLibraryTwoKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-animation-library-two-kit", surface: options.surface ?? "quaterniusAnimationLibraryTwo", createApi: ({ state }) => ({ snapshot: () => clone(state().animationClips.filter((clip) => clip.bank === "ual-two")), listClips: () => clone(state().animationClips.filter((clip) => clip.bank === "ual-two")), listCategories: () => [...new Set(state().animationClips.filter((clip) => clip.bank === "ual-two").map((clip) => clip.semantic))] }) }); }
export function createQuaterniusAnimationClipIndexKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-animation-clip-index-kit", surface: options.surface ?? "quaterniusAnimationClipIndex", createApi: ({ state }) => ({ snapshot: () => clone(state().animationClips), categorizeClip(name = "") { const lowered = String(name).toLowerCase(); return QUATERNIUS_ANIMATION_CATEGORIES.find((category) => lowered.includes(category.replace("-", "")) || lowered.includes(category)) ?? "unclassified"; }, listBySemantic: (semantic) => clone(state().animationClips.filter((clip) => clip.semantic === semantic)) }) }); }
export function createQuaterniusAnimationBankKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-animation-bank-kit", surface: options.surface ?? "quaterniusAnimationBank", createApi: ({ state }) => ({ snapshot: () => clone(state().animationClips), registerClip(clip = {}) { const next = { id: clip.id ?? stableId("clip", clip.semantic, clip.url), bank: clip.bank ?? "custom", semantic: clip.semantic ?? "unclassified", ...clip }; state().animationClips = [...state().animationClips.filter((item) => item.id !== next.id), next]; return clone(next); }, listClips: () => clone(state().animationClips), findBySemantic: (semantic) => clone(state().animationClips.filter((clip) => clip.semantic === semantic)), getLocomotionSet: () => Object.fromEntries(["idle", "walk", "run", "sprint"].map((semantic) => [semantic, state().animationClips.find((clip) => clip.semantic === semantic) ?? null])), getActionSet: (semantic) => clone(state().animationClips.filter((clip) => clip.semantic === semantic)), validateRequiredClips(required = ["idle", "walk", "run"]) { const issues = required.filter((semantic) => !state().animationClips.some((clip) => clip.semantic === semantic)).map((semantic) => `missing:${semantic}`); return { ok: issues.length === 0, issues }; } }) }); }
export function createQuaterniusRigProfileKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-rig-profile-kit", surface: options.surface ?? "quaterniusRigProfile", createApi: () => ({ snapshot: () => clone(QUATERNIUS_HUMANOID_RIG), getRequiredBones: () => clone(QUATERNIUS_HUMANOID_RIG.requiredBones) }) }); }
export function createQuaterniusRigBindingKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-rig-binding-kit", surface: options.surface ?? "quaterniusRigBinding", createApi: () => ({ snapshot: () => clone(QUATERNIUS_HUMANOID_RIG), checkBinding: checkRigBinding }) }); }
export function createQuaterniusRetargetCheckKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-retarget-check-kit", surface: options.surface ?? "quaterniusRetargetCheck", createApi: () => ({ snapshot: () => ({ sourceRig: clone(QUATERNIUS_HUMANOID_RIG) }), checkRetarget(targetRig = {}, clip = {}) { const binding = checkRigBinding(targetRig, clip); return { characterId: targetRig.id ?? "unknown-character", animationId: clip.id ?? "unknown-animation", status: binding.status, missingBones: binding.missingBones, missingTracks: binding.missingTracks, rootMotion: binding.rootMotion, notes: binding.issues }; } }) }); }
export function createQuaterniusRootMotionPolicyKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-root-motion-policy-kit", surface: options.surface ?? "quaterniusRootMotionPolicy", createApi: () => { const policies = ["in-place", "root-motion", "explicit", "ignore", "unknown"]; return { snapshot: () => clone(policies), normalizePolicy: (policy = "unknown") => policies.includes(policy) ? policy : "unknown", shouldUseControllerMotion: (policy = "unknown") => ["in-place", "ignore", "unknown"].includes(policy) }; } }); }
export function createQuaterniusRealAssetPlaybackCheckKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-real-asset-playback-check-kit", surface: options.surface ?? "quaterniusRealAssetPlaybackCheck", createApi: () => ({ snapshot: () => ({ required: ["character", "idle", "walk", "run"] }), checkAssets(manifest = {}) { const required = ["character", "idle", "walk", "run"]; const paths = { character: manifest.character, ...(manifest.clips ?? {}) }; const missing = required.filter((key) => !paths[key]); return { ok: missing.length === 0, status: missing.length === 0 ? "ready" : "missing-assets", missing, message: missing.length ? `Missing real Quaternius assets: ${missing.join(", ")}` : "Real asset playback manifest is ready." }; } }) }); }
function libraryKit(id, surface, collectionName) { return (nexusEngine = {}, options = {}) => defineKit(nexusEngine, { id: options.id ?? id, surface: options.surface ?? surface, createApi: ({ state }) => ({ snapshot: () => clone(state()[collectionName] ?? []), list: () => clone(state()[collectionName] ?? []), get: (id) => clone((state()[collectionName] ?? []).find((item) => item.id === id) ?? null) }) }); }
export const createQuaterniusMaterialAtlasKit = libraryKit("quaternius-material-atlas-kit", "quaterniusMaterialAtlas", "materialAtlases");
export const createQuaterniusPropLibraryKit = libraryKit("quaternius-prop-library-kit", "quaterniusPropLibrary", "packs");
export const createQuaterniusWorldPieceLibraryKit = libraryKit("quaternius-world-piece-library-kit", "quaterniusWorldPieceLibrary", "packs");
export const createQuaterniusCreatureLibraryKit = libraryKit("quaternius-creature-library-kit", "quaterniusCreatureLibrary", "packs");
export const createQuaterniusVehicleLibraryKit = libraryKit("quaternius-vehicle-library-kit", "quaterniusVehicleLibrary", "packs");
export function createQuaterniusWebgpuCharacterShaderKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-webgpu-character-shader-kit", surface: options.surface ?? "quaterniusWebgpuCharacterShader", provides: ["quaternius-webgpu-character-shader", "webgpu-shader-descriptor"], createApi: () => ({ snapshot: () => clone(QUATERNIUS_CHARACTER_SHADER_DESCRIPTOR), getShaderDescriptor: () => clone(QUATERNIUS_CHARACTER_SHADER_DESCRIPTOR), validate: () => ({ ok: QUATERNIUS_CHARACTER_SHADER_DESCRIPTOR.source.includes("@vertex") && QUATERNIUS_CHARACTER_SHADER_DESCRIPTOR.source.includes("@fragment"), issues: [] }) }) }); }
export function createQuaterniusWebgpuTerrainShaderKit(nexusEngine = {}, options = {}) { return defineKit(nexusEngine, { id: options.id ?? "quaternius-webgpu-terrain-shader-kit", surface: options.surface ?? "quaterniusWebgpuTerrainShader", provides: ["quaternius-webgpu-terrain-shader", "webgpu-shader-descriptor"], createApi: () => ({ snapshot: () => clone(QUATERNIUS_TERRAIN_SHADER_DESCRIPTOR), getShaderDescriptor: () => clone(QUATERNIUS_TERRAIN_SHADER_DESCRIPTOR), validate: () => ({ ok: QUATERNIUS_TERRAIN_SHADER_DESCRIPTOR.source.includes("@vertex") && QUATERNIUS_TERRAIN_SHADER_DESCRIPTOR.source.includes("@fragment"), issues: [] }) }) }); }
export function createQuaterniusPackLibraryKitSuite(nexusEngine = {}, options = {}) { return [createQuaterniusPackLibraryKit(nexusEngine, options.packLibrary), createQuaterniusPackCatalogKit(nexusEngine, options.packCatalog), createQuaterniusLicenseReceiptKit(nexusEngine, options.licenseReceipt), createQuaterniusFileIndexKit(nexusEngine, options.fileIndex), createQuaterniusRuntimePromotionKit(nexusEngine, options.runtimePromotion), createQuaterniusBaseCharacterKit(nexusEngine, options.baseCharacter), createQuaterniusCharacterCreatorKit(nexusEngine, options.characterCreator), createQuaterniusOutfitBuilderKit(nexusEngine, options.outfitBuilder), createQuaterniusEquipmentBuilderKit(nexusEngine, options.equipmentBuilder), createQuaterniusAnimationLibraryOneKit(nexusEngine, options.animationLibraryOne), createQuaterniusAnimationLibraryTwoKit(nexusEngine, options.animationLibraryTwo), createQuaterniusAnimationClipIndexKit(nexusEngine, options.animationClipIndex), createQuaterniusAnimationBankKit(nexusEngine, options.animationBank), createQuaterniusRigProfileKit(nexusEngine, options.rigProfile), createQuaterniusRigBindingKit(nexusEngine, options.rigBinding), createQuaterniusRetargetCheckKit(nexusEngine, options.retargetCheck), createQuaterniusRootMotionPolicyKit(nexusEngine, options.rootMotionPolicy), createQuaterniusRealAssetPlaybackCheckKit(nexusEngine, options.realAssetPlaybackCheck), createQuaterniusMaterialAtlasKit(nexusEngine, options.materialAtlas), createQuaterniusPropLibraryKit(nexusEngine, options.propLibrary), createQuaterniusWorldPieceLibraryKit(nexusEngine, options.worldPieceLibrary), createQuaterniusCreatureLibraryKit(nexusEngine, options.creatureLibrary), createQuaterniusVehicleLibraryKit(nexusEngine, options.vehicleLibrary), createQuaterniusWebgpuCharacterShaderKit(nexusEngine, options.webgpuCharacterShader), createQuaterniusWebgpuTerrainShaderKit(nexusEngine, options.webgpuTerrainShader) ]; }
export default createQuaterniusPackLibraryKit;
