import { clone, createDefinitionFactory, defineInjectedRuntimeKit, ensureResource, stableId } from "../protokit-core/index.js";

export const WGSL_SHADER_LIBRARY_KIT_VERSION = "0.1.0";
export const BASIC_WGSL = /* wgsl */ `
@group(0) @binding(0) var<uniform> time: f32;
struct VertexIn { @location(0) position: vec3<f32> };
struct VertexOut { @builtin(position) clip: vec4<f32> };
@vertex fn vs_main(input: VertexIn) -> VertexOut { var out: VertexOut; out.clip = vec4<f32>(input.position, 1.0); return out; }
@fragment fn fs_main(input: VertexOut) -> @location(0) vec4<f32> { return vec4<f32>(0.8, 0.9, 1.0, 1.0); }
`;
const list = (value) => value == null ? [] : Array.isArray(value) ? value.slice() : [value];
const makeState = () => ({ version: WGSL_SHADER_LIBRARY_KIT_VERSION, shaders: {}, diagnostics: [] });
function defineWgslKit(nexusEngine, config) { const { resource } = createDefinitionFactory(nexusEngine); const State = resource(config.resourceName || config.surface + ".state"); return defineInjectedRuntimeKit(nexusEngine, { id: config.id, resources: { State }, provides: list(config.provides || config.id), initWorld({ world }) { ensureResource(world, State, makeState); }, install({ engine, world }) { const state = () => ensureResource(world, State, makeState); engine.n = engine.n || {}; engine.n[config.surface] = config.createApi({ state, engine, world, State }); }, metadata: { version: WGSL_SHADER_LIBRARY_KIT_VERSION, stability: "prototype", purpose: config.id } }); }
export function extractWgslBindings(source = "") { const bindings = []; const pattern = /@group\((\d+)\)\s*@binding\((\d+)\)/g; let match; while ((match = pattern.exec(String(source)))) bindings.push({ group: Number(match[1]), binding: Number(match[2]) }); return bindings; }
export function extractWgslEntrypoints(source = "") { const entries = []; const pattern = /@(vertex|fragment|compute)\s+fn\s+([A-Za-z0-9_]+)/g; let match; while ((match = pattern.exec(String(source)))) entries.push({ stage: match[1], name: match[2] }); return entries; }
export function validateWgslDescriptor(descriptor = {}) { const issues = []; if (descriptor.language !== "wgsl") issues.push("language-not-wgsl"); if (!descriptor.source || !String(descriptor.source).trim()) issues.push("missing-source"); const entries = extractWgslEntrypoints(descriptor.source); const entryNames = new Set(entries.map((entry) => entry.name)); for (const name of Object.values(descriptor.stages || {})) if (name && !entryNames.has(name)) issues.push("missing-entrypoint:" + name); const declared = extractWgslBindings(descriptor.source).map((item) => item.group + ":" + item.binding); const described = list(descriptor.bindGroups).flatMap((group) => list(group.bindings).map((binding) => group.group + ":" + binding.binding)); for (const binding of declared) if (!described.includes(binding)) issues.push("binding-not-described:" + binding); return { ok: issues.length === 0, issues, entries, bindings: declared }; }
export function createShaderModuleDescriptor(descriptor = {}) { const validation = validateWgslDescriptor(descriptor); return { id: descriptor.id || stableId("wgsl-shader", descriptor.source), language: "wgsl", label: descriptor.label || descriptor.id || "wgsl-shader", source: descriptor.source || BASIC_WGSL, stages: descriptor.stages || { vertex: "vs_main", fragment: "fs_main" }, validation }; }
export function createWgslShaderLibraryKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-shader-library-kit", surface: options.surface || "wgslShaderLibrary", provides: ["wgsl-shader-library"], createApi: ({ state }) => ({ snapshot: () => clone(state()), registerShader(descriptor = {}) { const module = createShaderModuleDescriptor(descriptor); state().shaders[module.id] = module; if (!module.validation.ok) state().diagnostics.push({ shaderId: module.id, issues: module.validation.issues }); return clone(module); }, getShader: (id) => clone(state().shaders[id] || null), validateShader: validateWgslDescriptor }) }); }
export function createWgslInlineShaderKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-inline-shader-kit", surface: options.surface || "wgslInlineShader", createApi: () => ({ snapshot: () => ({ defaultSource: BASIC_WGSL }), createDescriptor(input = {}) { return { id: input.id || stableId("inline-wgsl", input.source || BASIC_WGSL), language: "wgsl", source: input.source || BASIC_WGSL, stages: input.stages || { vertex: "vs_main", fragment: "fs_main" }, bindGroups: input.bindGroups || [{ group: 0, bindings: [{ binding: 0, type: "uniform-buffer" }] }], fallback: input.fallback || "visible-error-surface" }; } }) }); }
export function createWgslShaderModuleKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-shader-module-kit", surface: options.surface || "wgslShaderModule", createApi: () => ({ snapshot: () => ({ moduleFactory: "descriptor-only" }), createShaderModuleDescriptor }) }); }
export function createWgslBindingCheckKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-binding-check-kit", surface: options.surface || "wgslBindingCheck", createApi: () => ({ snapshot: () => ({ parser: "regex-binding-contract" }), extractBindings: extractWgslBindings, validate: validateWgslDescriptor }) }); }
export function createWgslEntrypointCheckKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-entrypoint-check-kit", surface: options.surface || "wgslEntrypointCheck", createApi: () => ({ snapshot: () => ({ parser: "regex-entrypoint-contract" }), extractEntrypoints: extractWgslEntrypoints, validate: validateWgslDescriptor }) }); }
export function createWgslUniformLayoutKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-uniform-layout-kit", surface: options.surface || "wgslUniformLayout", createApi: () => ({ snapshot: () => ({ alignment: "descriptor-owned", minUniformBufferOffsetAlignment: 256 }), packSchema: (schema = {}) => ({ schema: clone(schema), alignment: 256, note: "Host renderer performs binary packing." }) }) }); }
export function createWgslShaderDiagnosticsKit(nexusEngine = {}, options = {}) { return defineWgslKit(nexusEngine, { id: options.id || "wgsl-shader-diagnostics-kit", surface: options.surface || "wgslShaderDiagnostics", createApi: ({ state }) => ({ snapshot: () => clone(state().diagnostics), report(diagnostic = {}) { const next = { id: diagnostic.id || stableId("wgsl-diagnostic", diagnostic.shaderId, diagnostic.stage, diagnostic.message), ...diagnostic }; state().diagnostics.push(next); return clone(next); } }) }); }
export function createWgslShaderLibraryKitSuite(nexusEngine = {}, options = {}) { return [createWgslShaderLibraryKit(nexusEngine, options.library), createWgslInlineShaderKit(nexusEngine, options.inlineShader), createWgslShaderModuleKit(nexusEngine, options.shaderModule), createWgslBindingCheckKit(nexusEngine, options.bindingCheck), createWgslEntrypointCheckKit(nexusEngine, options.entrypointCheck), createWgslUniformLayoutKit(nexusEngine, options.uniformLayout), createWgslShaderDiagnosticsKit(nexusEngine, options.shaderDiagnostics)]; }
export default createWgslShaderLibraryKit;
