import { asList, clone, createDefinitionFactory, defineInjectedRuntimeKit, ensureResource } from "../protokit-core/index.js";

export const OBJAVERSE_MANIFEST_KIT_VERSION = "0.1.0";

export function createObjaverseManifestState(options = {}) { return { version: OBJAVERSE_MANIFEST_KIT_VERSION, manifest: clone(options.manifest ?? null), validation: { ok: false, errors: [] }, history: [] }; }
export function validateObjaverseManifest(manifest = {}) { const errors = []; if (!manifest || typeof manifest !== "object") errors.push("manifest must be object"); if (!manifest.version) errors.push("version missing"); if (!Array.isArray(manifest.assets)) errors.push("assets must be array"); for (const asset of asList(manifest.assets)) { if (!asset.id) errors.push("asset id missing"); if (!asset.kind) errors.push(`asset ${asset.id ?? "unknown"} kind missing`); } return { ok: errors.length === 0, errors }; }
export function resolveObjaverseAssetUrl(manifest = {}, asset = {}, path = "") { const base = String(manifest.assetBaseUrl ?? "").replace(/\/$/, ""); const value = String(path || asset.mesh || asset.url || "").replace(/^\//, ""); if (/^https?:/.test(value)) return value; return base ? `${base}/${value}` : value; }

export function createObjaverseManifestKit(nexusRealtime = {}, options = {}) { const { resource, event } = createDefinitionFactory(nexusRealtime); const State = resource(options.resourceName ?? "objaverseManifest.state"); const Updated = event("objaverseManifest.updated"); const initial = () => createObjaverseManifestState(options); return defineInjectedRuntimeKit(nexusRealtime, { id: options.id ?? "objaverse-manifest-kit", resources: { State }, events: { Updated }, provides: ["objaverse:manifest", "asset:manifest", "asset:manifest-validation"], initWorld({ world }) { ensureResource(world, State, initial); }, install({ engine, world }) { const state = () => ensureResource(world, State, initial); const publish = (next, evt) => { next.history = evt ? [evt, ...(next.history ?? [])].slice(0, 64) : next.history; world.setResource(State, next); world.emit?.(Updated, { state: clone(next), event: clone(evt) }); return clone(next); }; const api = { getState: state, registerManifest(manifest = {}) { const validation = validateObjaverseManifest(manifest); return publish({ ...state(), manifest: clone(manifest), validation }, { type: "manifest", ok: validation.ok }); }, validate() { const validation = validateObjaverseManifest(state().manifest ?? {}); return publish({ ...state(), validation }, { type: "validate", ok: validation.ok }); }, resolveAssetUrl(asset = {}, path = "") { return resolveObjaverseAssetUrl(state().manifest ?? {}, asset, path); }, listAssets(filter = {}) { return asList(state().manifest?.assets).filter((asset) => (!filter.kind || asset.kind === filter.kind) && (!filter.biome || asList(asset.biomes).includes(filter.biome))).map(clone); }, snapshot: () => clone(state()) }; engine.objaverseManifest = api; engine.n ??= {}; engine.n.objaverseManifest = api; }, metadata: { version: OBJAVERSE_MANIFEST_KIT_VERSION, purpose: "Bootstrap manifest registration, URL resolution, and validation for Objaverse-derived assets." } }); }

export default createObjaverseManifestKit;
