export const SPATIAL_AUTHORING_KITS_VERSION = "0.3.0";
export const REQUIRED_HAND_AUTHORING_KITS = Object.freeze(["webxr-hand-adapter-dsk","openxr-hand-adapter-dsk","hand-gesture-dsk","spatial-scene-graph-dsk","selection-dsk","transform-dsk","widget-dsk","interaction-dsk","persistence-dsk"]);

const clone = (value) => value == null ? value : JSON.parse(JSON.stringify(value));
const asArray = (value) => Array.isArray(value) ? value : value == null ? [] : [value];
const toNumber = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const frame = (world) => toNumber(world?.__nexusClock?.frame, 0);

export function requireNexus(NexusRealtime, name = "spatial authoring kit") {
  for (const key of ["defineRuntimeKit", "defineResource", "defineEvent"]) if (typeof NexusRealtime?.[key] !== "function") throw new TypeError(`${name} requires NexusRealtime.${key}.`);
}
export const vec3 = (value = {}, fallback = {}) => ({ x: toNumber(value.x, toNumber(fallback.x, 0)), y: toNumber(value.y, toNumber(fallback.y, 0)), z: toNumber(value.z, toNumber(fallback.z, 0)) });
export const quat = (value = {}, fallback = {}) => ({ x: toNumber(value.x, toNumber(fallback.x, 0)), y: toNumber(value.y, toNumber(fallback.y, 0)), z: toNumber(value.z, toNumber(fallback.z, 0)), w: toNumber(value.w, toNumber(fallback.w, 1)) });
export const normalizeTransform = (value = {}) => ({ space: String(value.space ?? "local-floor"), position: vec3(value.position), rotation: quat(value.rotation), scale: vec3(value.scale, { x: 1, y: 1, z: 1 }) });
export function normalizeSpatialObject(value = {}, index = 0) {
  const id = String(value.id ?? `object-${index}`).trim();
  if (!id) throw new TypeError("Spatial objects require a stable id.");
  return { id, type: String(value.type ?? "spatial.object"), name: String(value.name ?? id), tags: asArray(value.tags).map(String), parentId: value.parentId ?? null, transform: normalizeTransform(value.transform ?? {}), bounds: { center: vec3(value.bounds?.center), size: vec3(value.bounds?.size, { x: 0.4, y: 0.25, z: 0.04 }) }, capabilities: { selectable: value.capabilities?.selectable !== false, movable: value.capabilities?.movable !== false, resizable: value.capabilities?.resizable !== false, interactable: value.capabilities?.interactable !== false, persistent: value.capabilities?.persistent !== false }, widget: value.widget ? clone(value.widget) : null, interaction: value.interaction ? clone(value.interaction) : null, metadata: clone(value.metadata ?? {}) };
}

function def(id, engineKey, provides = [], requires = [], purpose = "") { return Object.freeze({ id, engineKey, provides, requires, purpose, category: id.includes("adapter") ? "adapter-dsk" : "hand-authoring-dsk" }); }
export const WEBXR_HAND_ADAPTER_DSK_DEFINITION = def("webxr-hand-adapter-dsk", "webxrHandAdapter", ["hand:adapter","webxr:hand-input"]);
export const OPENXR_HAND_ADAPTER_DSK_DEFINITION = def("openxr-hand-adapter-dsk", "openxrHandAdapter", ["hand:adapter","openxr:hand-input"]);
export const HAND_GESTURE_DSK_DEFINITION = def("hand-gesture-dsk", "handGestures", ["hand:gesture"], ["hand:adapter"]);
export const SPATIAL_SCENE_GRAPH_DSK_DEFINITION = def("spatial-scene-graph-dsk", "spatialScene", ["scene:graph"]);
export const SELECTION_DSK_DEFINITION = def("selection-dsk", "selection", ["selection:state"], ["scene:graph"]);
export const TRANSFORM_DSK_DEFINITION = def("transform-dsk", "transforms", ["transform:patches"], ["scene:graph","selection:state"]);
export const WIDGET_DSK_DEFINITION = def("widget-dsk", "widgets", ["widget:registry"], ["scene:graph"]);
export const INTERACTION_DSK_DEFINITION = def("interaction-dsk", "interactions", ["interaction:events"], ["scene:graph"]);
export const PERSISTENCE_DSK_DEFINITION = def("persistence-dsk", "persistence", ["persistence:snapshot"], ["scene:graph"]);
export const HAND_AUTHORING_DSK_DEFINITIONS = Object.freeze([WEBXR_HAND_ADAPTER_DSK_DEFINITION,OPENXR_HAND_ADAPTER_DSK_DEFINITION,HAND_GESTURE_DSK_DEFINITION,SPATIAL_SCENE_GRAPH_DSK_DEFINITION,SELECTION_DSK_DEFINITION,TRANSFORM_DSK_DEFINITION,WIDGET_DSK_DEFINITION,INTERACTION_DSK_DEFINITION,PERSISTENCE_DSK_DEFINITION]);
export const SPATIAL_AUTHORING_CONTRACTS = Object.freeze({ normalizedHandCommand: { type: "hand.gesture", actorId: "user", gesture: "point|pinch|grab|menu", ray: "plain descriptor", target: "object id or null" } });

function runtimeKit(N, definition, config, spec) { requireNexus(N, definition.id); return N.defineRuntimeKit({ id: config.kitId ?? definition.id, requires: definition.requires, provides: definition.provides, ...spec, metadata: { version: SPATIAL_AUTHORING_KITS_VERSION, status: "experimental", category: definition.category, purpose: definition.purpose } }); }
function makeStoreKit(N, definition, config, initial, apiFactory, phase = "simulate") {
  const State = N.defineResource(`${definition.id}.state`);
  const Input = N.defineEvent(`${definition.id}.input`);
  const Output = N.defineEvent(`${definition.id}.output`);
  const init = () => ({ version: SPATIAL_AUTHORING_KITS_VERSION, ...clone(initial) });
  function system(world) { let state = world.getResource(State) ?? init(); for (const event of world.readEvents(Input)) { state = apiFactory.reduce?.(state, event, world, Output) ?? state; } world.setResource(State, state); }
  return runtimeKit(N, definition, config, { resources: { State }, events: { Input, Output }, systems: [{ phase, name: `${definition.engineKey}System`, system }], initWorld({ world }) { world.setResource(State, init()); }, install({ engine, world }) { engine[definition.engineKey] = apiFactory.install(State, Input, world); }, bindings: { State } });
}
function adapterReduce(state, event, world, Output) { const command = { type: event.type ?? "hand.pose", actorId: event.actorId ?? "user", hand: event.hand ?? "right", gesture: event.gesture ?? event.type ?? "pose", confidence: Math.max(0, Math.min(1, toNumber(event.confidence, 1))), ray: event.ray ? clone(event.ray) : null, targetId: event.targetId ?? event.hit?.objectId ?? null, tick: frame(world) }; world.emit(Output, command); return { ...state, commands: [...state.commands.slice(-31), command], lastCommand: command }; }
function adapterInstall(State, Input, world) { return { input(payload = {}) { world.emit(Input, payload); return world.getResource(State); }, normalize(payload = {}) { return { ...payload, gesture: payload.gesture ?? payload.type ?? "pose" }; }, getState() { return world.getResource(State); } }; }
export function createWebXrHandAdapterDsk(N, config = {}) { return makeStoreKit(N, WEBXR_HAND_ADAPTER_DSK_DEFINITION, config, { provider: "webxr", commands: [], lastCommand: null }, { reduce: adapterReduce, install: adapterInstall }, "input"); }
export function createOpenXrHandAdapterDsk(N, config = {}) { return makeStoreKit(N, OPENXR_HAND_ADAPTER_DSK_DEFINITION, config, { provider: "openxr", commands: [], lastCommand: null }, { reduce: adapterReduce, install: adapterInstall }, "input"); }
export const createWebXRHandAdapterDsk = createWebXrHandAdapterDsk;
export const createOpenXRHandAdapterDsk = createOpenXrHandAdapterDsk;
export function createHandGestureDsk(N, config = {}) { return makeStoreKit(N, HAND_GESTURE_DSK_DEFINITION, config, { active: {}, recent: [], lastGesture: null }, { reduce(state, event, world, Output) { const gesture = { ...event, gesture: event.gesture ?? event.type ?? "pose", tick: frame(world) }; world.emit(Output, gesture); return { ...state, active: { ...state.active, [gesture.hand ?? "right"]: gesture }, recent: [...state.recent.slice(-31), gesture], lastGesture: gesture }; }, install: adapterInstall }, "input"); }
export function createSpatialSceneGraphDsk(N, config = {}) { const objects = {}; for (const [i, object] of asArray(config.objects).entries()) { const normalized = normalizeSpatialObject(object, i); objects[normalized.id] = normalized; } return makeStoreKit(N, SPATIAL_SCENE_GRAPH_DSK_DEFINITION, config, { sceneId: config.sceneId ?? "workspace", objects, patches: [], dirtyObjectIds: [] }, { reduce(state, event, world, Output) { const patch = event.patch ?? event; const next = { ...state, objects: { ...state.objects }, patches: [...state.patches, patch] }; if (patch.type === "createObject") { const object = normalizeSpatialObject(patch.object); next.objects[object.id] = object; next.dirtyObjectIds = [object.id]; } else if (patch.type === "updateObject" && next.objects[patch.objectId]) { next.objects[patch.objectId] = { ...next.objects[patch.objectId], ...clone(patch.partial ?? {}) }; next.dirtyObjectIds = [patch.objectId]; } world.emit(Output, { dirtyObjectIds: next.dirtyObjectIds }); return next; }, install(State, Input, world) { return { createObject(object) { world.emit(Input, { type: "createObject", object }); return world.getResource(State); }, updateObject(objectId, partial) { world.emit(Input, { type: "updateObject", objectId, partial }); return world.getResource(State); }, applyPatch(patch) { world.emit(Input, patch); return world.getResource(State); }, getObject(id) { return world.getResource(State)?.objects?.[id] ?? null; }, getState() { return world.getResource(State); } }; } }); }
export function createSelectionDsk(N, config = {}) { return makeStoreKit(N, SELECTION_DSK_DEFINITION, config, { selectedObjectIds: [], hoveredObjectId: null }, { reduce(state, event, world, Output) { const id = event.objectId ?? event.targetId; const next = id ? { ...state, selectedObjectIds: [id], hoveredObjectId: id } : state; world.emit(Output, next); return next; }, install(State, Input, world) { return { pointSelect(payload = {}) { world.emit(Input, payload); return world.getResource(State); }, clear() { world.setResource(State, { version: SPATIAL_AUTHORING_KITS_VERSION, selectedObjectIds: [], hoveredObjectId: null }); return world.getResource(State); }, getState() { return world.getResource(State); } }; } }); }
export function createTransformDsk(N, config = {}) { return makeStoreKit(N, TRANSFORM_DSK_DEFINITION, config, { lastPatch: null }, { reduce(state, event, world) { const ids = asArray(event.targetIds ?? event.objectId); const partial = event.position ? { transform: { position: vec3(event.position) } } : event.scale ? { transform: { scale: vec3(event.scale) } } : {}; for (const id of ids) world.emit({ name: "spatialSceneGraph.state.patch" }, { type: "updateObject", objectId: id, partial }); return { ...state, lastPatch: { ids, partial } }; }, install(State, Input, world) { return { move(targetIds, position) { world.emit(Input, { targetIds, position }); return world.getResource(State); }, resize(targetIds, scale) { world.emit(Input, { targetIds, scale }); return world.getResource(State); }, getState() { return world.getResource(State); } }; } }); }
export function createWidgetDsk(N, config = {}) { return makeStoreKit(N, WIDGET_DSK_DEFINITION, config, { types: ["panel", "note", "timer", "button"], instances: {} }, { reduce(state, event, world) { const type = event.type ?? "panel"; const id = event.id ?? `${type}-${Object.keys(state.instances).length + 1}`; return { ...state, instances: { ...state.instances, [id]: { type, props: clone(event.props ?? {}) } }, lastCreatedObjectId: id }; }, install(State, Input, world) { return { create(type, props = {}, transform = {}) { world.emit(Input, { type, props, transform }); return world.getResource(State); }, getState() { return world.getResource(State); } }; } }); }
export function createInteractionDsk(N, config = {}) { return makeStoreKit(N, INTERACTION_DSK_DEFINITION, config, { history: [], lastInteraction: null }, { reduce(state, event, world, Output) { const record = { actorId: event.actorId ?? "user", targetId: event.targetId ?? event.objectId, verb: event.verb ?? "press", payload: clone(event.payload ?? {}), tick: frame(world) }; world.emit(Output, record); return { ...state, history: [...state.history.slice(-31), record], lastInteraction: record }; }, install(State, Input, world) { return { request(payload = {}) { world.emit(Input, payload); return world.getResource(State); }, press(targetId, actorId = "user") { world.emit(Input, { targetId, actorId, verb: "press" }); return world.getResource(State); }, getState() { return world.getResource(State); } }; } }); }
export function createPersistenceDsk(N, config = {}) { return makeStoreKit(N, PERSISTENCE_DSK_DEFINITION, config, { snapshots: {}, currentSnapshotId: null, lastSerialized: null }, { reduce(state, event, world) { const id = event.id ?? `snapshot-${Object.keys(state.snapshots).length + 1}`; const snapshot = { id, label: event.label ?? id, tick: frame(world), scene: clone(world.getResource({ name: "spatialSceneGraph.state" })), widgets: clone(world.getResource({ name: "widget-dsk.state" })) }; return { ...state, snapshots: { ...state.snapshots, [id]: snapshot }, currentSnapshotId: id, lastSerialized: JSON.stringify(snapshot) }; }, install(State, Input, world) { return { capture(label = "snapshot") { world.emit(Input, { label }); return world.getResource(State); }, serialize() { return world.getResource(State)?.lastSerialized ?? JSON.stringify(world.getResource(State)); }, getState() { return world.getResource(State); } }; } }); }

export function createHandAuthoringDsks(NexusRealtime, config = {}) { const cfg = config ?? {}; return [createWebXrHandAdapterDsk(NexusRealtime, cfg.webxrHand ?? {}), createOpenXrHandAdapterDsk(NexusRealtime, cfg.openxrHand ?? {}), createHandGestureDsk(NexusRealtime, cfg.handGestures ?? {}), createSpatialSceneGraphDsk(NexusRealtime, cfg.scene ?? {}), createSelectionDsk(NexusRealtime, cfg.selection ?? {}), createTransformDsk(NexusRealtime, cfg.transform ?? {}), createWidgetDsk(NexusRealtime, cfg.widgets ?? {}), createInteractionDsk(NexusRealtime, cfg.interactions ?? {}), createPersistenceDsk(NexusRealtime, cfg.persistence ?? {})]; }
export const createSpatialAuthoringKits = createHandAuthoringDsks;
export const createSpatialSceneGraphKit = createSpatialSceneGraphDsk;
export const createSelectionDomainServiceKit = createSelectionDsk;
export const createTransformDomainServiceKit = createTransformDsk;
export const createWidgetDomainServiceKit = createWidgetDsk;
export const createInteractionDomainServiceKit = createInteractionDsk;
export const createPersistenceDomainServiceKit = createPersistenceDsk;
export default createHandAuthoringDsks;
