import { createStreamSessionKit } from "../stream-session-kit/index.js";
import { createStreamChannelKit } from "../stream-channel-kit/index.js";
import { createStreamSubscriptionKit } from "../stream-subscription-kit/index.js";
import { createStreamBackpressureKit } from "../stream-backpressure-kit/index.js";
import { createStreamDeltaApplyKit } from "../stream-delta-apply-kit/index.js";
import { createObjaverseManifestKit } from "../objaverse-manifest-kit/index.js";
import { createObjaverseManifestRegisterKit } from "../objaverse-manifest-register-kit/index.js";
import { createObjaverseObjectStreamKit } from "../objaverse-object-stream-kit/index.js";
import { createObjaverseMetadataDeltaKit } from "../objaverse-metadata-delta-kit/index.js";
import { createObjaverseAvailabilityStreamKit } from "../objaverse-availability-stream-kit/index.js";
import { createObjaverseProvenanceKit } from "../objaverse-provenance-kit/index.js";
import { createObjaverseLicenseKit } from "../objaverse-license-kit/index.js";
import { createObjaverseAssetQualityKit } from "../objaverse-asset-quality-kit/index.js";
import { createObjaverseScaleNormalizationKit } from "../objaverse-scale-normalization-kit/index.js";
import { createObjaversePreviewKit } from "../objaverse-preview-kit/index.js";
import { createObjaverseImpostorDescriptorKit } from "../objaverse-impostor-descriptor-kit/index.js";
import { createObjectFamilyKit } from "../object-family-kit/index.js";
import { createObjectVariantSelectionKit } from "../object-variant-selection-kit/index.js";
import { createObjectLodPolicyKit } from "../object-lod-policy-kit/index.js";
import { createObjectMaterialVariantKit } from "../object-material-variant-kit/index.js";
import { createObjectGroundingProfileKit } from "../object-grounding-profile-kit/index.js";
import { createObjectImportProfileKit } from "../object-import-profile-kit/index.js";
import { createObjectImportTransformKit } from "../object-import-transform-kit/index.js";
import { createObjectBoundsDescriptorKit } from "../object-bounds-descriptor-kit/index.js";
import { createObjectPivotAnchorKit } from "../object-pivot-anchor-kit/index.js";
import { createObjectMeshRequestKit } from "../object-mesh-request-kit/index.js";
import { createObjectResidencyKit } from "../object-residency-kit/index.js";
import { createMeshChunkStreamKit } from "../mesh-chunk-stream-kit/index.js";
import { createMeshAssemblyDescriptorKit } from "../mesh-assembly-descriptor-kit/index.js";
import { createObjectInstanceStreamKit } from "../object-instance-stream-kit/index.js";
import { createPatchObjectBatchKit } from "../patch-object-batch-kit/index.js";
import { createObjectStaticBatchKit } from "../object-static-batch-kit/index.js";
import { createObjectBatchDeltaKit } from "../object-batch-delta-kit/index.js";
import { createObjectBatchLifecycleKit } from "../object-batch-lifecycle-kit/index.js";
import { createSimulationInterestKit } from "../simulation-interest-kit/index.js";
import { createWorldPatchStreamKit } from "../world-patch-stream-kit/index.js";
import { createObjectStateStreamKit } from "../object-state-stream-kit/index.js";
import { createEnvironmentFieldStreamKit } from "../environment-field-stream-kit/index.js";
import { createObjectStreamPriorityKit } from "../object-stream-priority-kit/index.js";
import { createObjectStreamPlanKit } from "../object-stream-plan-kit/index.js";

export const OBJAVERSE_RUNTIME_OBJECT_KIT_VERSION = "0.1.0";
export function createObjaverseRuntimeObjectKits(NexusRealtime = {}, config = {}) { const c = config ?? {}; return [createStreamSessionKit(NexusRealtime, c.streamSession ?? {}), createStreamChannelKit(NexusRealtime, c.streamChannel ?? {}), createStreamSubscriptionKit(NexusRealtime, c.streamSubscription ?? {}), createStreamBackpressureKit(NexusRealtime, c.streamBackpressure ?? {}), createStreamDeltaApplyKit(NexusRealtime, c.streamDeltaApply ?? {}), createObjaverseManifestKit(NexusRealtime, c.manifest ?? {}), createObjaverseManifestRegisterKit(NexusRealtime, c.manifestRegister ?? {}), createObjaverseObjectStreamKit(NexusRealtime, c.objectStream ?? {}), createObjaverseMetadataDeltaKit(NexusRealtime, c.metadataDelta ?? {}), createObjaverseAvailabilityStreamKit(NexusRealtime, c.availability ?? {}), createObjaverseProvenanceKit(NexusRealtime, c.provenance ?? {}), createObjaverseLicenseKit(NexusRealtime, c.license ?? {}), createObjaverseAssetQualityKit(NexusRealtime, c.quality ?? {}), createObjaverseScaleNormalizationKit(NexusRealtime, c.scale ?? {}), createObjaversePreviewKit(NexusRealtime, c.preview ?? {}), createObjaverseImpostorDescriptorKit(NexusRealtime, c.impostor ?? {}), createObjectFamilyKit(NexusRealtime, c.objectFamily ?? {}), createObjectVariantSelectionKit(NexusRealtime, c.variantSelection ?? {}), createObjectLodPolicyKit(NexusRealtime, c.lodPolicy ?? {}), createObjectMaterialVariantKit(NexusRealtime, c.materialVariant ?? {}), createObjectGroundingProfileKit(NexusRealtime, c.grounding ?? {}), createObjectImportProfileKit(NexusRealtime, c.importProfile ?? {}), createObjectImportTransformKit(NexusRealtime, c.importTransform ?? {}), createObjectBoundsDescriptorKit(NexusRealtime, c.bounds ?? {}), createObjectPivotAnchorKit(NexusRealtime, c.pivotAnchor ?? {}), createObjectMeshRequestKit(NexusRealtime, c.meshRequest ?? {}), createObjectResidencyKit(NexusRealtime, c.residency ?? {}), createMeshChunkStreamKit(NexusRealtime, c.meshChunkStream ?? {}), createMeshAssemblyDescriptorKit(NexusRealtime, c.meshAssembly ?? {}), createObjectInstanceStreamKit(NexusRealtime, c.instanceStream ?? {}), createPatchObjectBatchKit(NexusRealtime, c.patchBatch ?? {}), createObjectStaticBatchKit(NexusRealtime, c.staticBatch ?? {}), createObjectBatchDeltaKit(NexusRealtime, c.batchDelta ?? {}), createObjectBatchLifecycleKit(NexusRealtime, c.batchLifecycle ?? {}), createSimulationInterestKit(NexusRealtime, c.simulationInterest ?? {}), createWorldPatchStreamKit(NexusRealtime, c.worldPatchStream ?? {}), createObjectStateStreamKit(NexusRealtime, c.objectStateStream ?? {}), createEnvironmentFieldStreamKit(NexusRealtime, c.environmentFieldStream ?? {}), createObjectStreamPriorityKit(NexusRealtime, c.streamPriority ?? {}), createObjectStreamPlanKit(NexusRealtime, c.streamPlan ?? {})]; }
export default createObjaverseRuntimeObjectKits;
