import { asList, clone, createDefinitionFactory, defineInjectedRuntimeKit, ensureResource, number } from "../protokit-core/index.js";

export const OBJAVERSE_MANIFEST_REGISTER_KIT_VERSION = "0.1.0";

export function createObjaverseManifestRegisterState() { return { version: OBJAVERSE_MANIFEST_REGISTER_KIT_VERSION, registered: {}, count: 0, history: [] }; }

export function createObjaverseManifestRegisterKit(nexusEngine = {}, options = {}) { const { resource, event } = createDefinitionFactory(nexusEngine); const State = resource(options.resourceName ?? "objaverseManifestRegister.state"); const Updated = event("objaverseManifestRegister.updated"); const initial = () => createObjaverseManifestRegisterState(options); return defineInjectedRuntimeKit(nexusEngine, { id: options.id ?? "objaverse-manifest-register-kit", resources: { State }, events: { Updated }, requires: ["objaverse:manifest", "objaverse:catalog", "object:families"], provides: ["objaverse:manifest-register", "asset:catalog-registration"], initWorld({ world }) { ensureResource(world, State, initial); }, install({ engine, world }) { const state = () => ensureResource(world, State, initial); const publish = (next, evt) => { next.history = evt ? [evt, ...(next.history ?? [])].slice(0, 64) : next.history; world.setResource(State, next); world.emit?.(Updated, { state: clone(next), event: clone(evt) }); return clone(next); }; const registerAsset = (asset = {}) => { engine.objaverseCatalog?.register?.(asset); engine.objectFamily?.registerFamily?.(asset); engine.objaverseMetadataIndex?.register?.({ assetId: asset.id, tags: asset.tags, categories: [asset.kind, asset.family].filter(Boolean), refs: { metadata: asset.metadata, preview: asset.preview } }); const next = state(); next.registered[asset.id] = { id: asset.id, at: number(world?.__nexusClock?.elapsed, 0) }; next.count = Object.keys(next.registered).length; return publish(next, { type: "asset", id: asset.id }); }; const api = { getState: state, registerAsset, registerAll() { const assets = engine.objaverseManifest?.listAssets?.() ?? []; return asList(assets).map(registerAsset); }, snapshot: () => clone(state()) }; engine.objaverseManifestRegister = api; engine.n ??= {}; engine.n.objaverseManifestRegister = api; }, metadata: { version: OBJAVERSE_MANIFEST_REGISTER_KIT_VERSION, purpose: "Registers manifest assets into catalog, family, and metadata domain kits." } }); }

export default createObjaverseManifestRegisterKit;
